version: '2'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"