version: '2'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/db
      - JWT_SECRET_KEY=B010B514AD927302CD6601063436B51B2ED1BFC7945DF3426796243FB356AC7F
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"